type Mutation {
  newMenu(name: String!, price: Int!, quantity: Int!): Boolean!
  orderMenu(menuId: ID!): Boolean!
  updateMenu(menuId: ID!, name: String, quantity: Int, price: Int): Boolean!
  deleteMenu(menuId: ID!): Boolean!
}
