type Query {
  allMenu: [Menu!]!
  typeMenu(type: String!): [Menu!]!
  user(_id: ID!): User!
}

type User {
  _id: ID!
  name: String!
  email: String!
}

type Menu {
  _id: ID!
  name: String!
  price: Int!
  quantity: Int!
  img: String!
  type: String!
}
